### ISSUE TITLE
[功能需求]切换模型功能

### ISSUE THREAD

**Issue by ShanShuWu** [MirrorCY/rryth#10]
大佬，api有别的模型可以用吗?有些tag用anything还是有些出入，如果可以的话。希望未来可以有切换模型的功能。
感谢大佬提供免费api

**Comment by MirrorCY** [comment]
模型切换将在近期上线，支持用户提供 sd-webui 作为绘画后端。

**Comment by ShanShuWu** [comment]
哇，太强了
