### ISSUE TITLE
打擾一下，請問該項目還能繼續正常作為產圖娛樂使用嗎？謝謝

### ISSUE THREAD

**Issue by Wowuu88** [MirrorCY/rryth#14]
經過友人介紹才知道這個，但似乎被告知已經無法使用了，是嗎？

或是有類似的替代方案呢？感恩：）

**Comment by Wowuu88** [comment]
（我發現表達得有些語病，還請您見諒~）

**Comment by MirrorCY** [comment]
有个正常维护的 fork，插件市场搜索 rr2

**Comment by MirrorCY** [comment]
![Screenshot_2024-11-26-00-08-58-05_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://github.com/user-attachments/assets/ec4426c8-e857-4757-aaea-1d7138d01a03)
