### ISSUE TITLE
启用自动翻译后，会中英互译

### ISSUE THREAD

**Issue by vlssu** [MirrorCY/rryth#4]
启用后虽然中文可以翻译成英文，但是也会加入部分中文内容
而直接输入英文后会被翻译成中文，并且会缺失大量词条，导致无法正常使用

希望打开 `是否启用自动翻译` 按钮后，指定 中译英或者其他，总之，需要最终输出是为英文，而不是其他。

**Comment by MirrorCY** [comment]
fixed by #5
