### ISSUE TITLE
大佬请问以下你的anything3.0模型在哪里下载的，我的好像和你的不一样

### ISSUE THREAD

**Issue by lux-QAQ** [MirrorCY/rryth#6]
都是anyting3模型，同样的tag 种子 分辨率 出的图。结果我发现我自己的模型出的图好差。我发现你的anyting3模型的hash和我不一样。我才意识到是模型不一样。你能分享下你的anything3模型的下载链接吗

**Comment by MirrorCY** [comment]
https://huggingface.co/Linaqruf/anything-v3.0/blob/main/Anything-V3.0-pruned-fp16.safetensors
