### ISSUE TITLE
【bug】iphone QQ消息加载失败，windows端QQ正常

### ISSUE THREAD

**Issue by ParadiseWitch** [MirrorCY/rryth#9]
# iphone
![$PZN`)0WDKON2B5RYGNT2 C](https://user-images.githubusercontent.com/37146904/212443858-ba015525-1fa4-47e8-bace-f3a5dc88bf49.jpg)
![MP9O15Z3T2_C}L_(ZR~9F)C](https://user-images.githubusercontent.com/37146904/212443861-d3e85957-11e7-4d84-a685-8ce25d98f389.jpg)

# windows
![image](https://user-images.githubusercontent.com/37146904/212443887-fa9b7f12-67fa-4fc4-b403-6024f1fe1821.png)
![image](https://user-images.githubusercontent.com/37146904/212443895-36d5f822-cba7-48e6-a4ed-8bd4981b65c1.png)

**Comment by MirrorCY** [comment]
合并转发这个问题是 QQ 独有的，与插件无关。

**Comment by MirrorCY** [comment]
有时候重启一下就能打开了。总之消息已经正确的发送到了 QQ，无法被显示是 QQ 的问题~
